# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraBranch < Formula
  desc "Create a jira branch for a ticket"
  homepage "https://github.com/manuphatak/jira-branch"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.4/jira-branch_0.2.4_Darwin_x86_64.tar.gz"
      sha256 "b113bf72851c5c1853cdfa07faa675e712f2d00cc800aadc33cb139b53def372"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.4/jira-branch_0.2.4_Darwin_arm64.tar.gz"
      sha256 "09ec27a1d9b8ab208b673e61d754a7a09e6c05bf2758a62466b10d53ae54762b"

      def install
        bin.install "jira-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.4/jira-branch_0.2.4_Linux_x86_64.tar.gz"
      sha256 "b09f3847a1c7f3ce5ac503777575679303239391e13ae3f476ec8489b28537f3"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.4/jira-branch_0.2.4_Linux_arm64.tar.gz"
      sha256 "e8c58d64938fb77770367c1175bc783eed369e0e4827d2d07061f32964909648"

      def install
        bin.install "jira-branch"
      end
    end
  end
end
